import type { FieldDef, ResourceDef } from "./fields";
import {
  BANNER_PLACEMENTS,
  JOB_DEPARTMENTS,
  JOB_LOCATIONS,
  JOB_TYPES,
  NEWS_CATEGORIES,
  PRODUCT_CATEGORIES,
} from "./options";

const sortField: FieldDef = {
  name: "sort",
  label: "Thứ tự hiển thị",
  type: "number",
  defaultValue: 0,
  help: "Số nhỏ hiển thị trước.",
};
const activeField: FieldDef = {
  name: "active",
  label: "Hiển thị trên website",
  type: "boolean",
  defaultValue: true,
};

export const RESOURCES: ResourceDef[] = [
  {
    key: "banners",
    table: "banners",
    label: "Banner",
    singular: "banner",
    icon: "image",
    description: "Ảnh banner đầu trang của từng trang. Nếu vị trí có nhiều banner đang bật, website dùng banner có thứ tự nhỏ nhất.",
    titleField: "placement",
    listColumns: ["image", "placement", "sort", "active"],
    orderBy: "placement ASC, sort ASC, id ASC",
    publishField: "active",
    fields: [
      { name: "placement", label: "Vị trí", type: "select", required: true, options: BANNER_PLACEMENTS },
      { name: "image", label: "Ảnh banner", type: "image", required: true, help: "Khuyến nghị 1920×1080 px trở lên." },
      { name: "imageAlt", label: "Mô tả ảnh (alt)", type: "i18n-text", maxLength: 200 },
      { name: "link", label: "Liên kết khi bấm (tuỳ chọn)", type: "text", maxLength: 500 },
      sortField,
      activeField,
    ],
  },
  {
    key: "services",
    table: "services",
    label: "Dịch vụ gia công mạ",
    singular: "dịch vụ",
    icon: "science",
    titleField: "title",
    listColumns: ["image", "title", "code", "sort", "active"],
    searchFields: ["title", "code", "slug"],
    orderBy: "sort ASC, id ASC",
    publishField: "active",
    fields: [
      { name: "title", label: "Tên dịch vụ", type: "i18n-text", required: true, maxLength: 200 },
      { name: "slug", label: "Đường dẫn (slug)", type: "text", required: true, maxLength: 120, slugOf: "title", help: "Chữ thường, không dấu, nối bằng gạch ngang. Để trống sẽ tự sinh từ tên." },
      { name: "code", label: "Mã dịch vụ", type: "text", maxLength: 60, help: "Ví dụ HAN-SRV-ENP-03" },
      { name: "titleEn", label: "Tên tiếng Anh kỹ thuật", type: "text", maxLength: 200 },
      { name: "badge", label: "Nhãn nổi bật (tuỳ chọn)", type: "i18n-text", maxLength: 100 },
      { name: "description", label: "Mô tả ngắn", type: "i18n-textarea", required: true, maxLength: 1000 },
      { name: "applicationLabel", label: "Tiêu đề khối ứng dụng", type: "i18n-text", maxLength: 100 },
      { name: "applicationText", label: "Nội dung ứng dụng", type: "i18n-text", maxLength: 300 },
      { name: "statLabel", label: "Chỉ số nổi bật", type: "i18n-text", maxLength: 150 },
      { name: "image", label: "Ảnh đại diện", type: "image", required: true },
      { name: "imageAlt", label: "Mô tả ảnh (alt)", type: "i18n-text", maxLength: 200 },
      sortField,
      activeField,
    ],
  },
  {
    key: "products",
    table: "products",
    label: "Sản phẩm & Dự án",
    singular: "sản phẩm/dự án",
    icon: "precision_manufacturing",
    titleField: "title",
    listColumns: ["image", "title", "categorySlug", "lot", "sort", "active"],
    searchFields: ["title", "lot", "slug"],
    orderBy: "sort ASC, id ASC",
    publishField: "active",
    fields: [
      { name: "title", label: "Tên sản phẩm/dự án", type: "i18n-text", required: true, maxLength: 250 },
      { name: "slug", label: "Đường dẫn (slug)", type: "text", required: true, maxLength: 120, slugOf: "title" },
      { name: "categorySlug", label: "Danh mục", type: "select", required: true, options: PRODUCT_CATEGORIES },
      { name: "lot", label: "Mã lô / mã dự án", type: "text", maxLength: 60, help: "Ví dụ HN-PRD-882" },
      { name: "description", label: "Mô tả ngắn", type: "i18n-textarea", required: true, maxLength: 1200 },
      { name: "image", label: "Ảnh đại diện", type: "image", required: true },
      { name: "imageAlt", label: "Mô tả ảnh (alt)", type: "i18n-text", maxLength: 200 },
      { name: "imageBadge", label: "Nhãn góc ảnh (tuỳ chọn)", type: "i18n-text", maxLength: 120 },
      {
        name: "specChips",
        label: "Thông số kỹ thuật nổi bật",
        type: "list",
        maxItems: 8,
        itemFields: [
          { name: "label", label: "Tên thông số", type: "i18n-text", maxLength: 80 },
          { name: "value", label: "Giá trị", type: "i18n-text", maxLength: 120 },
        ],
      },
      { name: "showInGrid", label: "Hiện trong lưới danh mục", type: "boolean", defaultValue: true },
      { name: "featured", label: "Thẻ lớn (nổi bật) trong lưới", type: "boolean", defaultValue: false },
      { name: "spotlight", label: "Dự án tiêu biểu (khối lớn cuối trang)", type: "boolean", defaultValue: false, help: "Nên chỉ bật cho 1 mục; nếu bật nhiều, website lấy mục đầu tiên." },
      sortField,
      activeField,
    ],
  },
  {
    key: "clients",
    table: "clients",
    label: "Khách hàng tiêu biểu",
    singular: "khách hàng",
    icon: "handshake",
    description: "Danh sách công ty khách hàng chạy ngang ở trang Giới thiệu. Chưa có logo thì website hiện tên công ty bằng chữ.",
    titleField: "name",
    listColumns: ["logo", "name", "legalName", "sort", "active"],
    searchFields: ["name", "legal_name"],
    orderBy: "sort ASC, id ASC",
    publishField: "active",
    fields: [
      { name: "name", label: "Tên công ty / thương hiệu", type: "text", required: true, maxLength: 120, help: "Hiển thị lớn trên thẻ khi chưa có logo, và làm văn bản thay thế của logo." },
      { name: "legalName", label: "Tên pháp lý đầy đủ (tuỳ chọn)", type: "text", maxLength: 250, help: "Hiển thị nhỏ bên dưới logo." },
      { name: "logo", label: "Logo", type: "image", help: "Nên dùng PNG/SVG nền trong suốt hoặc nền trắng, bản ngang, tối thiểu 400 px bề rộng." },
      sortField,
      activeField,
    ],
  },
  {
    key: "posts",
    table: "posts",
    label: "Tin tức",
    singular: "bài viết",
    icon: "newspaper",
    titleField: "title",
    listColumns: ["image", "title", "categoryKey", "publishedAt", "status"],
    searchFields: ["title", "slug", "author"],
    orderBy: "published_at DESC, id DESC",
    publishField: "status",
    fields: [
      { name: "title", label: "Tiêu đề", type: "i18n-text", required: true, maxLength: 300 },
      { name: "slug", label: "Đường dẫn (slug)", type: "text", required: true, maxLength: 120, slugOf: "title" },
      { name: "categoryKey", label: "Chuyên mục", type: "select", required: true, options: NEWS_CATEGORIES },
      { name: "techBadge", label: "Nhãn kỹ thuật (tuỳ chọn)", type: "text", maxLength: 80, help: "Ví dụ ISO/IEC 17025" },
      { name: "excerpt", label: "Tóm tắt", type: "i18n-textarea", required: true, maxLength: 1000 },
      { name: "body", label: "Nội dung bài viết", type: "i18n-textarea", maxLength: 50000, help: "Ngăn đoạn bằng dòng trống. Dòng bắt đầu bằng '## ' là tiêu đề mục, '- ' là gạch đầu dòng." },
      { name: "image", label: "Ảnh đại diện", type: "image", required: true },
      { name: "imageAlt", label: "Mô tả ảnh (alt)", type: "i18n-text", maxLength: 200 },
      { name: "author", label: "Tác giả", type: "i18n-text", maxLength: 120 },
      { name: "authorRole", label: "Chức danh tác giả", type: "i18n-text", maxLength: 120 },
      {
        name: "metrics",
        label: "Chỉ số kỹ thuật nổi bật (chỉ hiện ở bài tiêu điểm)",
        type: "list",
        maxItems: 3,
        itemFields: [
          { name: "label", label: "Tên chỉ số", type: "i18n-text", maxLength: 60 },
          { name: "value", label: "Giá trị", type: "i18n-text", maxLength: 60 },
        ],
      },
      { name: "readTime", label: "Thời gian đọc", type: "i18n-text", maxLength: 40, help: "Ví dụ: 5 phút đọc" },
      { name: "publishedAt", label: "Ngày đăng", type: "date", required: true },
      { name: "featured", label: "Bài tiêu điểm (khối lớn đầu trang tin tức)", type: "boolean", defaultValue: false },
      {
        name: "status",
        label: "Trạng thái",
        type: "select",
        required: true,
        defaultValue: "published",
        options: [
          { value: "published", label: "Đã đăng" },
          { value: "draft", label: "Bản nháp" },
        ],
      },
    ],
  },
  {
    key: "jobs",
    table: "jobs",
    label: "Tuyển dụng",
    singular: "vị trí tuyển dụng",
    icon: "work",
    titleField: "title",
    listColumns: ["title", "department", "jobType", "location", "sort", "active"],
    searchFields: ["title", "slug"],
    orderBy: "sort ASC, id ASC",
    publishField: "active",
    fields: [
      { name: "title", label: "Vị trí tuyển dụng", type: "i18n-text", required: true, maxLength: 200 },
      { name: "slug", label: "Đường dẫn (slug)", type: "text", required: true, maxLength: 120, slugOf: "title" },
      { name: "department", label: "Bộ phận", type: "select", required: true, options: JOB_DEPARTMENTS },
      { name: "jobType", label: "Hình thức", type: "select", required: true, options: JOB_TYPES },
      { name: "location", label: "Nơi làm việc", type: "select", required: true, options: JOB_LOCATIONS },
      { name: "salary", label: "Mức lương", type: "i18n-text", maxLength: 100 },
      { name: "deadline", label: "Hạn nộp hồ sơ", type: "i18n-text", maxLength: 100 },
      {
        name: "tags",
        label: "Thẻ yêu cầu chính",
        type: "list",
        maxItems: 8,
        itemFields: [{ name: "text", label: "Nội dung thẻ", type: "i18n-text", maxLength: 80 }],
      },
      { name: "description", label: "Mô tả công việc", type: "i18n-textarea", maxLength: 10000 },
      { name: "requirements", label: "Yêu cầu ứng viên", type: "i18n-textarea", maxLength: 10000 },
      { name: "benefits", label: "Quyền lợi", type: "i18n-textarea", maxLength: 10000 },
      sortField,
      activeField,
    ],
  },
];

export function getResource(key: string): ResourceDef | undefined {
  return RESOURCES.find((r) => r.key === key);
}
