import {
  Award,
  BadgeCheck,
  BookOpen,
  BrainCircuit,
  Briefcase,
  CalendarDays,
  Car,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  ClipboardCheck,
  Clock,
  Cog,
  Construction,
  Cpu,
  Download,
  Droplet,
  Droplets,
  ExternalLink,
  Factory,
  FileCheck,
  FileText,
  FileUp,
  FlaskConical,
  Flame,
  Funnel,
  Gauge,
  Gift,
  Globe,
  HardHat,
  Handshake,
  Headset,
  Image,
  Inbox,
  Layers,
  Leaf,
  LibraryBig,
  ListChecks,
  LoaderCircle,
  Lock,
  Mail,
  MailCheck,
  MailPlus,
  MapPin,
  Maximize,
  Menu,
  MessageCircle,
  Microscope,
  Newspaper,
  Package,
  Paperclip,
  Phone,
  PhoneCall,
  PlaneTakeoff,
  Radar,
  Ruler,
  Search,
  SearchCheck,
  Send,
  Shield,
  ShieldCheck,
  ShieldPlus,
  Ship,
  SlidersHorizontal,
  SprayCan,
  Terminal,
  TrendingUp,
  Upload,
  User,
  Waves,
  Wind,
  Cylinder,
  X,
  ZoomIn,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  createLucideIcon,
  type LucideIcon,
} from "lucide-react";

/* Lucide v1 đã bỏ icon thương hiệu → vẽ lại cùng bộ nét (24x24, stroke) để đồng bộ với phần còn lại. */
const Facebook = createLucideIcon("facebook", [
  ["path", { d: "M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z", key: "f" }],
]);
const Youtube = createLucideIcon("youtube", [
  ["path", { d: "M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17", key: "b" }],
  ["path", { d: "m10 15 5-3-5-3z", key: "p" }],
]);
const Linkedin = createLucideIcon("linkedin", [
  ["path", { d: "M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z", key: "a" }],
  ["rect", { width: "4", height: "12", x: "2", y: "9", key: "r" }],
  ["circle", { cx: "4", cy: "4", r: "2", key: "c" }],
]);
const Instagram = createLucideIcon("instagram", [
  ["rect", { width: "20", height: "20", x: "2", y: "2", rx: "5", ry: "5", key: "r" }],
  ["path", { d: "M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z", key: "p" }],
  ["line", { x1: "17.5", x2: "17.51", y1: "6.5", y2: "6.5", key: "l" }],
]);

/**
 * Bộ icon duy nhất của website (Lucide, nét 1.75, bo tròn).
 * Giữ nguyên tên Material cũ làm khoá để dữ liệu CMS/seed đã lưu `icon: "science"`… vẫn chạy.
 * Thêm icon: import ở trên + khai báo một dòng trong MAP.
 */
const MAP: Record<string, LucideIcon> = {
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  east: ArrowRight,
  attach_file: Paperclip,
  biotech: Microscope,
  calendar_month: CalendarDays,
  calendar_today: CalendarDays,
  call: Phone,
  card_giftcard: Gift,
  chat: MessageCircle,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  cleaning_services: SprayCan,
  close: X,
  cloud_upload: Upload,
  construction: Construction,
  cyclone: Wind,
  directions_boat: Ship,
  directions_car: Car,
  domain_verification: SearchCheck,
  download: Download,
  eco: Leaf,
  electric_meter: Gauge,
  engineering: HardHat,
  error: CircleAlert,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  factory: Factory,
  file_present: FileCheck,
  filter_alt: Funnel,
  flight_takeoff: PlaneTakeoff,
  forward_to_inbox: MailPlus,
  fullscreen: Maximize,
  handshake: Handshake,
  health_and_safety: ShieldPlus,
  image: Image,
  inventory_2: Package,
  keyboard_arrow_up: ChevronUp,
  language: Globe,
  layers: Layers,
  library_books: LibraryBig,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  mail: Mail,
  mark_email_read: MailCheck,
  mark_email_unread: Inbox,
  memory: Cpu,
  menu: Menu,
  menu_book: BookOpen,
  model_training: BrainCircuit,
  newspaper: Newspaper,
  open_in_new: ExternalLink,
  person: User,
  phone_in_talk: PhoneCall,
  precision_manufacturing: Cog,
  progress_activity: LoaderCircle,
  request_quote: FileText,
  rule: ListChecks,
  schedule: Clock,
  science: FlaskConical,
  search: Search,
  security: Shield,
  send: Send,
  sensors: Radar,
  shield: Shield,
  shield_with_heart: ShieldCheck,
  straighten: Ruler,
  support_agent: Headset,
  terminal: Terminal,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload_file: FileUp,
  valve: Cylinder,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  water: Waves,
  water_drop: Droplet,
  water_ec: Droplets,
  work: Briefcase,
  workspace_premium: Award,
  zoom_in: ZoomIn,
  // Mạng xã hội / kênh liên hệ (khoá = tên kênh trong CMS)
  zalo: MessageCircle,
  facebook: Facebook,
  youtube: Youtube,
  linkedin: Linkedin,
  instagram: Instagram,
};

const HAS_SIZE = /(^|\s)text-(\[\d|xs\b|sm\b|base\b|lg\b|xl\b|\dxl\b)/;

export default function Icon({ name, className = "" }: { name: string; className?: string }) {
  const Cmp = MAP[name] ?? CircleHelp;
  return (
    <Cmp
      aria-hidden="true"
      width="1em"
      height="1em"
      strokeWidth={1.75}
      // Giữ nét 1.75px cố định theo mọi kích thước (thay cho absoluteStrokeWidth của lucide,
      // vốn tính ra NaN khi width="1em").
      className={`inline-block shrink-0 align-middle [&_*]:[vector-effect:non-scaling-stroke] ${className}`.trim()}
      style={HAS_SIZE.test(className) ? undefined : { fontSize: 24 }}
    />
  );
}
